# Change these first
owner: fresherr # Your GitHub organization or username, where this repository lives
repo: treeum-uptime # The name of this repository

sites:
  - name: finance.ua
    url: https://finance.ua
  - name: finance/insurance
    url: https://finance.ua/ua/insurance
  - name: finance/greencard
    url: https://finance.ua/ua/insurance/greencard
  - name: finance/osago
    url: https://finance.ua/ua/insurance/osago
  - name: finance/travel
    url: https://finance.ua/ua/insurance/travel
  - name: finance/credits
    url: https://finance.ua/ua/credits/all
  - name: finance/cards
    url: https://finance.ua/ua/cards
  - name: finance/news
    url: https://news.finance.ua
  - name: finance/rvk
    url: https://finance.ua/ua/banks/a-bank
  - name: minfin.com.ua
    url: https://minfin.com.ua
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#  cname: demo.upptime.js.org
  baseUrl: /treeum-uptime
  logoUrl: https://treeum.net/images/tild6238-3866-4136-b734-383832373432__treeum.png
  name: Uptime
#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/fresherr/treeum-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO